name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure CMake
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-windows
          path: ./build/Release/endstone_*.dll

  build-debian:
    name: Build on Debian
    runs-on: ubuntu-latest

    container:
      image: debian:stable

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Clang
        run: |
          apt-get update
          apt-get install -y cmake clang libc++-dev libc++abi-dev git

      - name: Configure CMake
        run: cmake -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang

      - name: Build
        run: cmake --build build --config Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-debian
          path: ./build/endstone_*.so